name: Build APKs

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Build APKs
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: senmanga-extension-apk
          path: "**/*.apk"
          retention-days: 7
